env:
  global:
    - CC_TEST_REPORTER_ID=294312eb9a02b4a4e04e4e8ad46ffc0a18ec7d03a3e186eabb885361d5bcb22c

language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
addons:
    apt:
        packages:
            - ed
install:
    - pip install .

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: nosetests

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
